name = "vite-cms"
pages_build_output_dir = "./dist"
compatibility_date = "2024-04-03"

[[kv_namespaces]]
binding = "KV"
id = "430321d1d7a4461db899f89df59d926f"

[[r2_buckets]]
binding = "R2"
bucket_name = "vite-cms"
