name = "vite-cms"
main = "src/index.ts"
compatibility_date = "2024-03-29"
compatibility_flags = ["nodejs_compat"]

# [vars]
# MY_VARIABLE = "production_value"

[[kv_namespaces]]
binding = "pages"
id = "430321d1d7a4461db899f89df59d926f"
preview_id = "391042132f3249e3a3dff46db520f422"
